version: '3'
services:
    ezworker:
        image: ezworker:latest
        container_name: ezworker-instance
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 5000:5000
