# first stage to install all package
FROM python:3.6.11
RUN pip3 install --no-cache-dir bs4 selenium PyExecJS flask requests
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN apt-get install -y nodejs vim
WORKDIR /root/
CMD ["./run.sh"]
