version: '3'
services:
    ezworker:
        image: ezworker:latest
        container_name: ezworker-instance
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 5000:5000
    ezworker-debug:
        image: ezworker-debug:latest
        container_name: ezworker-instance-debug
        volumes:
            - ./:/root
        build:
            context: .
            dockerfile: ./Dockerfile.debug
        ports:
            - 5001:5000
