# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4 selenium PyExecJS flask requests
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
    - name: run test
      run: |
        cd worker
        if [[ $(python3 ./format-checker.py | grep "correct" | wc -l) -ne 3 ]]; then
          exit 1
        fi
